AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for Lambda Deploy"

Resources:
  TestLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRunTimes:
        - nodejs16.x
      LayerName: arn:aws:lambda:us-east-2:121511844673:layer:mongodb:3
  TestLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "lambda-test"
      Description: "testing lambda"
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 512
      Timeout: 120
      Code:
        ZipFile: |
          exports.handler = async (event) => {console.log(event);return 'Hello from Lambda!';};
      Role: arn:aws:iam::121511844673:role/offline_lambda_role
      Layers:
        - !Ref TestLayer