AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for Lambda Deploy"

Resources:
  TestLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "lambda-test-inline"
      Description: "testing lambda"
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 512
      Timeout: 120
      Code:
        Zip: |
          const { MongoClient } = require("mongodb");

          exports.handler = async (event) => {
          	const filter = {
          		'orderNumber': '123'
          	};
          	const client = await MongoClient.connect(
          		'mongodb+srv://btanneru:Bhani4chinni@dev0.aar2e.mongodb.net/test?authSource=admin&replicaSet=dev0-shard-0&readPreference=primary&ssl=true',
          		{ useNewUrlParser: true, useUnifiedTopology: true }
          	);
          	const coll = client.db('smartCell_Commons').collection('order');
          	const cursor = coll.find(filter);
          	const result = await cursor.toArray();
          	console.log(`result:: ${result}`);
          	await client.close();
          	return result;
          };
      Role: arn:aws:iam::121511844673:role/offline_lambda_role
      Layers:
        - 'arn:aws:lambda:us-east-2:121511844673:layer:mongodb:3'